### PR TITLE
Priority shuffle

### PR DESCRIPTION
**Pull request by mfrederickson**
@garci66 it says that it wont be able to automatically merge.  I'm still creating this so you can see what was done but if you have trouble merging it into your branch, then we can just close your PR and I can create a new one which includes your original work.

### CODE REVIEW

**Comment by garci66** [comment]
Damn... ok... im getting confused. Code is almost the same in the conflict file but need to find which one is the good version. I'm sorry.

**Comment by garci66** [comment]
Im a bit confused since your branch has also the strict-priority shuffle which as been re-written (and re-comented) into a nicer style. It seems to be pretty much identical except it uses `|s| s.contents.present?` instead of `s.contents.length>0` and some cleanup of the lambda functions for max_by.

If the version on your branch works, then great.. let's use that one...

**Comment by mfrederickson** [comment]
Yeah, I didn't mean to cause problems there, sorry.  Yep, I just make some changes suggested by rubocop.  It works.

**Comment by garci66** [comment]
And thanks for adding all the test cases. This is a great helps!

**Comment by garci66** [comment]
So I guess we can close my PR. Your branch seems to have the cleaned up / re-styled version of strict_priority which is what we needed all along. Thanks again!

**Comment by garci66** [comment]
I guess the only thing is that it didn't seem to make it to the 2.3.4 branch

**Pull request closed without merging**
